### PR TITLE
Removed unnecessary print statements and optimised

### PR DESCRIPTION
**Pull request by aniketfuryrocks**

### CODE REVIEW

**Comment by diogoeichert** [comment]
I appreciate the collaboration and I've been thinking about removing the output for a while now, but these changes go way beyond that. Can you elaborate on the other changes? Thanks.

**Comment by aniketfuryrocks** [comment]
+ Removed print statements
+ throw Error if the dir does not exist
+ prevent checking if dir exists on every recursion

**Comment by aniketfuryrocks** [comment]
You might also want to promisify the recursion to prevent waiting for file to be deleted

**Comment by diogoeichert** [comment]
Sounds good. I shall do a proper review later today.

**Pull request merged**
